In [2]:
#Numpy
import numpy as np

In [5]:
#P1 - Create a null vector of size 10 but fifth value which is 7
p1_arr = np.zeros(10, dtype="int32")
p1_arr[4] = 7

p1_arr

array([0, 0, 0, 0, 7, 0, 0, 0, 0, 0], dtype=int32)

In [82]:
#P2 - Create a vector with values ranging from 10 to 24
p2_arr = np.arange(10,25)
p2_arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [11]:
#P3 - Create a 3x3 matrix with values ranging from 0 to 9       
p3_arr = np.arange(start=0, stop=9)
p3_arr = p3_arr.reshape(3,3)
p3_arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [33]:
#P4 - Create a 3x3x3 array with random values
p4_arr = np.random.randint(10, size=27)
p4_arr = p4_arr.reshape(3,3,3)
p4_arr

array([[[6, 9, 2],
        [4, 2, 7],
        [2, 5, 7]],

       [[7, 8, 0],
        [0, 0, 7],
        [2, 8, 0]],

       [[4, 0, 0],
        [7, 1, 0],
        [2, 7, 7]]])

In [84]:
#P5 - Create an array of size 12 with integer random values with one digit and sort it. (Use random.random(10, size=12))
p5_arr = np.random.randint(10, size=12)
p5_arr.sort()
p5_arr

array([2, 2, 3, 4, 5, 5, 6, 6, 7, 8, 9, 9])

In [83]:
#P6 - Create an array with 30 random values of one integer (from 0 to 100) and generate it as series.
p6_arr = np.random.randint(101, size=30)
p6_arr

array([37, 19,  4, 58, 80, 96, 72, 80, 23, 79, 29, 37, 86,  0, 96,  8, 48,
       43, 69, 41, 73, 38,  3, 44, 64, 46, 12, 37, 20, 25])

In [37]:
import pandas as pd

In [41]:
tit_df = pd.read_csv("titanic_train.csv")
tit_df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [70]:
tit_sp_df = tit_df[ (tit_df['Survived'] == 1) & (tit_df['Age'] <= 22) & (tit_df['Sex'] == 'male')]
print("The number of survived male under 22 was %d people" % len(tit_sp_df))

The number of survived male under 22 was 31 people


In [81]:
tit_p_df = tit_df[tit_df['Pclass'] == 1]['Fare']
print("The average fare of 1st class passengers was %lf" % (tit_p_df.sum() / len(tit_p_df)))

The average fare of 1st class passengers was 84.154687
